### ISSUE TITLE
Strange fan values

### ISSUE THREAD

**Issue by DrTron** [shred/pyquaero#2]
Hello,

I'm trying pyquaero for the first time (since my really old software finally has quit working). I get correct values for most of the parameter, just the fans are not correct. I'm running firmware version 1030 on my aquaero5 (never updated because of compatibility issues). There should be 4 fans running at 33% (1-3) and 40% (4) right now, but I get this. The first seems to be correct, but not the following ones.

Any ideas?
Thanks!

json.fans = [];
json.fans[0] = {};
json.fans[0].current = 0.0;
json.fans[0].power = 33.0;
json.fans[0].speed = 599;
json.fans[0].voltage = 3.95;
json.fans[1] = {};
json.fans[1].current = 33.0;
json.fans[1].power = 0.0;
json.fans[1].speed = 396;
json.fans[1].voltage = 5.97;
json.fans[2] = {};
json.fans[2].current = 0.0;
json.fans[2].power = 40.0;
json.fans[2].speed = 445;
json.fans[2].voltage = 4.76;
json.fans[3] = {};
json.fans[3].current = 0.0;
json.fans[3].power = 0.0;
json.fans[3].speed = 0;
json.fans[3].voltage = 0.0;
json.fans[4] = {};
json.fans[4].current = 0.0;
json.fans[4].power = 0.0;
json.fans[4].speed = 0;
json.fans[4].voltage = 0.0;
json.fans[5] = {};
json.fans[5].current = 0.0;
json.fans[5].power = 0.0;
json.fans[5].speed = 0;
json.fans[5].voltage = 0.0;
json.fans[6] = {};
json.fans[6].current = 0.0;
json.fans[6].power = 0.0;
json.fans[6].speed = 0;
json.fans[6].voltage = 0.0;
json.fans[7] = {};
json.fans[7].current = 0.0;
json.fans[7].power = 0.0;
json.fans[7].speed = 0;
json.fans[7].voltage = 0.0;
json.fans[8] = {};
json.fans[8].current = 4.12;
json.fans[8].power = 0.55;
json.fans[8].speed = 257;
json.fans[8].voltage = 12.2;
json.fans[9] = {};
json.fans[9].current = 0.0;
json.fans[9].power = 655.35;
json.fans[9].speed = 65535;
json.fans[9].voltage = 0.0;
json.fans[10] = {};
json.fans[10].current = 0.0;
json.fans[10].power = 0.0;
json.fans[10].speed = 0;
json.fans[10].voltage = 0.0;
json.fans[11] = {};
json.fans[11].current = 0.0;
json.fans[11].power = 0.0;
json.fans[11].speed = 0;
json.fans[11].voltage = 0.0;

**Comment by shred** [comment]
Firmware 1030 is not on the list of supported firmwares. However I am still actively using firmware 1036 (because never touch a running system). It seems that both firmwares share the same structure version. This is why pyquaero is accepting your firmware, too.

I have no way to install your firmware version, so all I can offer is a bit of remote debugging. There is a tool in pyquaero, called `pyqmdump`. You can send me the output files, and I can have a quick look for differences to my dump of firmware 1036.

Please invoke the tool like this:

```
pyqmdump --noflash --i-mean-it
```

It will generate two binary files called `status-*.bin` and `settings-*.bin`. Please send me these files. They do not contain any personal or sensitive data, but you can also send them by mail if you prefer.

(`--noflash` just means that the content of the flash memory is _not_ dumped. I have no use for that dump here, and it's also potentially risky. If you want to dump the flash contents out of curiosity, I recommend to restart the Aquaero after that, by powering it down for a few seconds.)

**Comment by DrTron** [comment]
Hello Richard,

thank you very much for your swift reply and for your support. I totally overlooked that the firmware page said "1036" instead of "1030", but I agree with you with not to change a running system. So even though this is a pure linux box, I may have a virtual windows installed somewhere, which I once (years and years ago) used to configure the aquaero properly. So I think as a last resort I could upgrade the firmware (not sure if that would give me 2101 or something even newer), but as you already mentioned, there is no going back from that.

I have attached the dump files, maybe 1030 is not so much different from your 1036 so we can make it work. Github does not accept .bin files, so I just added a .txt suffix.

Thanks!

[settings-1030-1013.bin.txt](https://github.com/shred/pyquaero/files/4612219/settings-1030-1013.bin.txt)
[status-1030-1013.bin.txt](https://github.com/shred/pyquaero/files/4612220/status-1030-1013.bin.txt)

**Comment by DrTron** [comment]
Oh, and BTW, I have another aquaero5 in another system running firmware 2009, which is also not mentioned on the firmware page but works just fine. Just in case you would like to have that dump, also.

**Comment by shred** [comment]
Thank you for the dump files. Yes, please send the 2009 dumps as well. I'll have a look if I can quickly add them to the list of supported firmwares. :smile:

Is pyquaero able to set the time on your Aquaero with firmware 1030? I have found an old note of mine, saying that there was a major change in the USB protocol between firmware 1030 to 1036. Actually I'm surprised that pyquaero can access your Aquaero at all.

**Comment by DrTron** [comment]
No, pyquaero is not able to set the time on the 1030 firmware (although that is a feature I don't really miss, but which is probably important for your reverse-engineering). pyquaero and my current readout software (aerocli) report the same date, but the time differs by 5 hours. As I am at UTC-5, pyquaero probably gives UTC and aerocli local time.

I'll upload the 2009 dump files tonight.

**Comment by shred** [comment]
I hopefully fixed that problem in commit 58dd1be1. Can you give it a try?

In another commit, I've changed pyqmdump, so `--noflash` is the default now. If you want to make a dump of the status and settings with the version in master, just use `pyqmdump --i-mean-it` instead.

**Comment by DrTron** [comment]
Thanks a lot to @shred for the really fast update. pyquaero is now working flawlessly with firmware 1030 (and almost working with 2009). That was really awesome.

I'll buy you a beer!

**Comment by shred** [comment]
1030 firmware was fixed in commit 58dd1be1. 2009 firmware was fixed in commit 620fe996. I will release a new version today.

@DrTron Thank you for your help. It has taken the project a good step forward. :+1: 

I'm closing this bug now. Feel free to reopen it if you find other problems in firmware 1030.
