### ISSUE TITLE
octo

### ISSUE THREAD

**Issue by rbirkelbach** [shred/pyquaero#4]
Hello,
will there be work on integrating functionality to use the octo controller by aquacomputer?
Best,
Robert

**Comment by shred** [comment]
Hi Robert!

No, unfortunately. At least, I won't do it.

The problem is that Aqua Computer does not release any protocol specifications. To add the Octo controller, firstly I would have to get the hardware, and secondly I would have to reverse-engineer the USB protocol (with uncertain outcome).

As this project is not related to Aqua Computer, I would have to spend the money and invest the time by myself. As I don't have a personal use of the Octo controller, I just selfishly won't do any work to add it. :wink: Sorry...

Best,
Richard
